# Generated by Django 3.0.7 on 2020-10-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=122)),
                ('url', models.CharField(max_length=2200)),
                ('desc', models.TextField()),
            ],
        ),
    ]
